version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      # from https://discuss.circleci.com/t/circle-ci-v2-and-android-memory-issues/11207
      JVM_OPTS: "-Xmx1024m -XX:+PrintFlagsFinal -XX:+PrintGCDetails"
      _JAVA_OPTIONS: "-Xmx1024m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false"
    steps:
      - checkout
      - run: env
      - run: git submodule update --init
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "performance-tracking/build.gradle" }}-{{ checksum  "performance-tracking-plugin/build.gradle" }}-{{ checksum  "performance-tracking-core/build.gradle" }}-{{ checksum  "Stubs/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "performance-tracking/build.gradle" }}-{{ checksum  "performance-tracking-plugin/build.gradle" }}-{{ checksum  "performance-tracking-core/build.gradle" }}-{{ checksum  "Stubs/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check --info
      - store_artifacts:
          path: ~/code/performance-tracking-plugin/build/reports
          destination: plugin-reports/
      - store_artifacts:
          path: ~/code/performance-tracking/build/reports
          destination: runtime-reports/
      - store_artifacts:
          path: ~/code/performance-tracking-core/build/reports
          destination: core-reports/
      - store_test_results:
          path: ~/code/performance-tracking-plugin/build/test-results/test
      - store_test_results:
          path: ~/code/performance-tracking/build/test-results/testReleaseUnitTest
      - store_test_results:
          path: ~/code/performance-tracking-core/build/test-results/test
      - run: bash <(curl -s https://codecov.io/bash)
